# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/jesusg/UnrealEngine
GAMEPROJECTFILE =/home/jesusg/Development/SkateGame/SkateGame.uproject

TARGETS = \
	SkateGame-Linux-DebugGame  \
	SkateGame-Linux-Shipping  \
	SkateGame \
	SkateGameEditor-Linux-DebugGame  \
	SkateGameEditor-Linux-Shipping  \
	SkateGameEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SkateGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SkateGameEditor-Linux-Debug


SkateGame-Linux-DebugGame:
	 $(PROJECTBUILD) SkateGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SkateGame-Linux-Shipping:
	 $(PROJECTBUILD) SkateGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SkateGame:
	 $(PROJECTBUILD) SkateGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SkateGameEditor-Linux-DebugGame:
	 $(PROJECTBUILD) SkateGameEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SkateGameEditor-Linux-Shipping:
	 $(PROJECTBUILD) SkateGameEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SkateGameEditor:
	 $(PROJECTBUILD) SkateGameEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
